#!/bin/bash

# Trigger this script using ./vhost sitename, ie. "./vhost drupal"

# This script helps set up the following:
# * A directory under webroot, containing a docroot directory for docroot and tmp.
# * Create an Apache Vhost, using mod macro.
# * Add an entry to the hosts file, using $DOMAIN as the domain.
# * Create an empty MySQL database using the supplied db authentication.

if [ $# -eq 0 ]; then
  echo "Usage: $0 sitename"
  exit;
fi;

USER=${SUDO_USER:-$USER} # if sudo use sudo var, otherwise use user. http://stackoverflow.com/a/14106940/687274
SITENAME=$1
WEBROOT="/home/$USER/sites"
DOMAIN='local'
VHOSTNAME='sites'
DB_USER='root'
DB_PASS='123'


if [ -d "${WEBROOT}/${SITENAME}" ]; then
  echo "The site: $SITENAME already appears to exist."
  exit 1;
fi

if [ $(id -u) != "0" ]
then
  echo 'Attempting to append sudo..'
  sudo "$0" "$@" 
  exit $?
fi

echo "Commencing site setup for: $SITENAME"

# Create the skeleton
echo "Creating directory skeleton"
mkdir $WEBROOT/$SITENAME
mkdir $WEBROOT/$SITENAME/docroot
mkdir $WEBROOT/$SITENAME/tmp
chown $USER:$USER $WEBROOT/$SITENAME -R

# Add an entry to apache
echo "Adding VHost to Apache"
echo "Use VHost $SITENAME" >> /etc/apache2/sites-available/$VHOSTNAME
/etc/init.d/apache2 restart

# Add an entry to hosts
echo "Adding entry to /etc/hosts"
echo "127.0.1.1 $SITENAME.$DOMAIN" >> /etc/hosts

# Create empty database. Need the wrapping backticks to allow database names with dashes
echo "Creating empty database with root credentials"
mysql -u $DB_USER -p$DB_PASS -e "create database \`$SITENAME\`;"

# Drush alias
echo "<?php
 \$aliases['$SITENAME'] = array(
   'uri' => '$SITENAME.$DOMAIN',
   '_root' => '$WEBROOT/$SITENAME/docroot',
  );?>
  " >> ~/.drush/aliases.drushrc.php

echo "Done."
